### ISSUE TITLE
Prototipo físico de la estación de recarga

### ISSUE THREAD

**Issue by 234laura** [234laura/ElectroEstaciones#2]

**Comment by AndresOrduz65** [comment]
[Modelo 3D Electroestacion.pdf](https://github.com/234laura/ElectroEstaciones/files/13192983/Modelo.3D.Electroestacion.pdf)

**Comment by AndresOrduz65** [comment]
![Captura de pantalla 2023-10-27 151622](https://github.com/234laura/ElectroEstaciones/assets/141773190/0e91a95d-7b49-406e-85c7-cc045180778d)
![Captura de pantalla 2023-10-27 151701](https://github.com/234laura/ElectroEstaciones/assets/141773190/da1cb4d4-6572-4326-b911-c24ed85b92dd)
![Captura de pantalla 2023-10-27 151732](https://github.com/234laura/ElectroEstaciones/assets/141773190/636afe38-469b-4d8d-8158-06c0f1ac9722)

**Comment by AndresOrduz65** [comment]
![image](https://github.com/234laura/ElectroEstaciones/assets/141773190/d7ce58c0-e2d5-4a2d-aead-ac40a58d0f85)

**Comment by AndresOrduz65** [comment]
![image](https://github.com/234laura/ElectroEstaciones/assets/141773190/ae88aef7-e624-407a-a183-500b525e0d20)
Vista Frontal*

**Comment by AndresOrduz65** [comment]
![Captura de pantalla 2023-11-08 191602](https://github.com/234laura/ElectroEstaciones/assets/141773190/9216095e-76be-4942-a98f-6867714867aa)
Perdón pero AutoCAD no me dejo acotar esa linea en especifico
